# Hora de Colocar a Mão na Massa com NumPy

## 1. Básico

1. Crie um numpy array **np_alturas** a partir da lista **alturas** que contém a altura de alguns jogadores de futebol em centímetros.

In [4]:
import numpy as np
np.__version__

'1.15.4'

In [5]:
alturas = [180, 220, 210, 210, 188, 176, 209, 200]

In [6]:
np_alturas = np.array(alturas)


2. Mostre o array numpy **np_alturas** e verifique o resultado.

In [9]:
np_alturas

array([180, 220, 210, 210, 188, 176, 209, 200])

In [10]:
type(np_alturas)

numpy.ndarray

3. Crie um array numpy **np_alturas_em_metros** com as alturas dos jogadores convertidas para metros.

In [11]:
np_alturas_em_metros = np_alturas / 100

4. Mostre o array numpy **np_alturas_em_metros** e verifique o resultado.

In [12]:
np_alturas_em_metros

array([1.8 , 2.2 , 2.1 , 2.1 , 1.88, 1.76, 2.09, 2.  ])

5. Crie um numpy array **np_pesos** a partir da lista **pesos** que contém a altura de alguns jogadores de futebol em gramas.

In [13]:
pesos = [64000, 73500, 67800, 89000, 98000, 76800, 78600, 82300]

6. Mostre o array numpy **np_pesos** e verifique o resultado.

In [14]:
np_pesos = np.array(pesos)

7. Crie um array numpy **np_pesos_em_kilos** com as alturas dos jogadores convertidas para kilos.

In [15]:
np_pesos_em_kilos = np_pesos / 1000

8. Mostre o array numpy **np_pesos_em_kilos** e verifique o resultado.

In [16]:
np_pesos_em_kilos

array([64. , 73.5, 67.8, 89. , 98. , 76.8, 78.6, 82.3])

9. Calcule os IMCs dos jogadores e armazene-os no array numpy **np_imcs**. 

In [17]:
np_imcs = np_pesos_em_kilos / np_alturas_em_metros ** 2

10. Mostre o array **np_imcs** e verifique o resultado.

In [19]:
np_imcs

array([19.75308642, 15.18595041, 15.37414966, 20.1814059 , 27.7274785 ,
       24.79338843, 17.99409354, 20.575     ])

11. Mostre as dimensões dos arrays **np_alturas**, **np_pesos** e **np_imcs**.

In [20]:
np_alturas.shape

(8,)

In [22]:
np_pesos.shape

(8,)

In [23]:
np_imcs.shape

(8,)

## 2. Fatiamento

12. Mostre todos os ICMs acima de 21 no array **np_imcs**.

In [25]:
acima_de_21 = np_imcs > 21

In [26]:
acima_de_21

array([False, False, False, False,  True,  True, False, False])

In [27]:
np_imcs[acima_de_21]

array([27.7274785 , 24.79338843])

13. Mostre o quarto ICMC do array **np_imcs**.

In [28]:
np_imcs[3]

20.181405895691608

14. Imprime do primeiro ao quarto imc do array **np_imcs**

In [29]:
np_imcs[0:4]

array([19.75308642, 15.18595041, 15.37414966, 20.1814059 ])

## 3. Matrizes bidimensionais

15. Crie um array multidimensial **np_alturas_e_pesos** a partir da lista **alturas_e_pesos**.

In [31]:
alturas_e_pesos = [[180, 78400],
                   [215, 102700],
                   [210, 98500],
                   [188, 75200]]


In [32]:
np_alturas_e_pesos = np.array(alturas_e_pesos)

16. Mostre as dimensões ao array **np_alturas_e_pesos**.

In [33]:
np_alturas_e_pesos.shape

(4, 2)

In [34]:
np_alturas_e_pesos.shape[0]

4

In [35]:
np_alturas_e_pesos.shape[1]

2

17. Mostre o segundo elemento do array **np_alturas_e_pesos**.

In [36]:
np_alturas_e_pesos[0, 1]

78400

18. Selecione o segunda coluna do array np_alturas_e_pesos e armazene-a no array **np_pesos**

In [37]:
np_pesos = np_alturas_e_pesos[:, 1]

In [38]:
np_pesos

array([ 78400, 102700,  98500,  75200])

19. Inclua a lista **atualizacao** no array **np_alturas_e_pesos_atualizado**

In [78]:
atualizacao = [[173, 64500],
              [164, 58600],
              [180, 89100]]

In [79]:
np_atualizacao = np.array(atualizacao)

In [80]:
np_alturas_e_pesos_atualizado = np.append(np_alturas_e_pesos, atualizacao, axis=0)

In [81]:
np_alturas_e_pesos_atualizado

array([[   180,  78400],
       [   215, 102700],
       [   210,  98500],
       [   188,  75200],
       [   173,  64500],
       [   164,  58600],
       [   180,  89100]])

20. Converte as alturas e os pesos do array **np_alturas_e_pesos_atualizado** para metros e kilos respectivamente e armazene o resultado no **np_alturas_e_pesos_convertido**. Ao final mostre as dimensões do array criado.

In [82]:
np_fator_de_conversao   = np.array([0.01, 0.001])
np_alturas_e_pesos_convertido = np_alturas_e_pesos_atualizado * np_fator_de_conversao

In [83]:
np_alturas_e_pesos_convertido

array([[  1.8 ,  78.4 ],
       [  2.15, 102.7 ],
       [  2.1 ,  98.5 ],
       [  1.88,  75.2 ],
       [  1.73,  64.5 ],
       [  1.64,  58.6 ],
       [  1.8 ,  89.1 ]])

## 4. Estatística Básica

21. Mostre a média, a mediana e o desvio padrão das alturas e dos pesos do array **np_alturas_e_pesos_convertido**. Além disto investigue a correlação entre as alturas e os pesos.

In [84]:
print("Media das alturas: {}".format(np.mean(np_alturas_e_pesos_convertido[:, 0])))
print("Media dos pesos: {}".format(np.mean(np_alturas_e_pesos_convertido[:, 1])))
print("Mediana das alturas: {}".format(np.median(np_alturas_e_pesos_convertido[:, 0])))
print("Mediana dos pesos: {}".format(np.median(np_alturas_e_pesos_convertido[:, 1])))
print("Desv. Pad das alturas: {}".format(np.std(np_alturas_e_pesos_convertido[:, 0])))
print("Desv. Pad dos pesos: {}".format(np.std(np_alturas_e_pesos_convertido[:, 1])))

Media das alturas: 1.8714285714285717
Media dos pesos: 81.0
Mediana das alturas: 1.8
Mediana dos pesos: 78.4
Desv. Pad das alturas: 0.17471843237691004
Desv. Pad dos pesos: 15.386264746751984


In [85]:
np.corrcoef(np_alturas_e_pesos_convertido[:, 0], np_alturas_e_pesos_convertido[:, 1])

array([[1.        , 0.90977457],
       [0.90977457, 1.        ]])