# Hora de Colocar a Mão na Massa com NumPy

## 1. Básico

1. Crie um numpy array **np_alturas** a partir da lista **alturas** que contém a altura de alguns jogadores de futebol em centímetros.

In [2]:
alturas = [180, 215, 210, 210, 188, 176, 209, 200]

In [3]:
import numpy as np
np_alturas = np.array(alturas)

2. Mostre o array numpy **np_alturas** e verifique o resultado.

In [4]:
type(np_alturas)

numpy.ndarray

3. Crie um array numpy **np_altura_em_metros** com as alturas dos jogadores convertidas para metros.

In [5]:
np_alturas_em_metros = np_alturas / 100

4. Mostre o array numpy **np_altura_em_metros** e verifique o resultado.

In [6]:
np_alturas_em_metros

array([1.8 , 2.15, 2.1 , 2.1 , 1.88, 1.76, 2.09, 2.  ])

5. Crie um numpy array **np_pesos** a partir da lista **pesos** que contém a altura de alguns jogadores de futebol em gramas.

In [7]:
pesos = [64000, 73500, 67800, 89000, 98000, 76800, 78600, 82300]

6. Crie o array numpy **np_pesos** a partir da lista **pesos** e mostre o resultado.

In [11]:
np_pesos = np.array(pesos)
np_pesos

array([64000, 73500, 67800, 89000, 98000, 76800, 78600, 82300])

7. Crie um array numpy **np_pesos_em_kilos** com os pesos dos jogadores convertidas para kilos.

In [16]:
np_pesos_em_kilos = np.array(pesos) / 1000
np_pesos_em_kilos

array([64. , 73.5, 67.8, 89. , 98. , 76.8, 78.6, 82.3])

8. Calcule os IMCs dos jogadores e armazene-os no array numpy **np_imcs**. 

In [17]:
np_imcs = np_pesos_em_kilos / (np_alturas_em_metros ** 2)

10. Mostre o array **np_imcs** e verifique o resultado.

In [18]:
np_imcs

array([19.75308642, 15.90048675, 15.37414966, 20.1814059 , 27.7274785 ,
       24.79338843, 17.99409354, 20.575     ])

10. Mostre as dimensões dos arrays **np_alturas_em_metros**, **np_pesos_em_kilos** e **np_imcs**.

In [22]:
print(np_alturas_em_metros.shape)
print(np_pesos_em_kilos.shape)
print(np_imcs.shape)

(8,)
(8,)
(8,)


## 2. Fatiamento

11. Mostre todos os ICMs acima de 21 no array **np_imcs**.

In [23]:
acima_de_21 = np_imcs > 21 
np_imcs[acima_de_21]

array([27.7274785 , 24.79338843])

12. Mostre o quarto ICMC do array **np_imcs**.

In [24]:
np_imcs[3]

20.181405895691608

13. Imprime do primeiro ao quarto imc do array **np_imcs**

In [26]:
np_imcs[0]

19.753086419753085

## 3. Matrizes bidimensionais

14. Crie um array multidimensial **np_alturas_e_pesos** a partir da lista **alturas_e_pesos**.

In [9]:
alturas_e_pesos = [[180, 78400],
                   [215, 102700],
                   [210, 98500],
                   [188, 75200]]


In [27]:
np_alturas_e_pesos = np.array(alturas_e_pesos)

15. Mostre as dimensões ao array **np_alturas_e_pesos**.

In [28]:
np_alturas_e_pesos.shape

(4, 2)

16. Mostre o segundo elemento do array **np_alturas_e_pesos**.

In [29]:
np_alturas_e_pesos[0, 1]

78400

17. Selecione o segunda coluna do array np_alturas_e_pessos e armazene-a no array **no_alturas**

19. Inclua a lista **atualizacao** no array **np_alturas_e_pesos_atualizado**

In [10]:
atualizacao = [[173, 64500],
              [164, 58600],
              [180, 89100]]

20. Converte as alturas e os pesos do array **np_alturas_e_pesos_atualizado** para metros e kilos respectivamente e armazene o resultado no **np_alturas_e_pesos_convertido**. Ao final mostre as dimensões do array criado.

## 4. Estatística Básica

21. Mostre a média, a mediana e o desvio padrão das alturas e dos pesos do array **np_alturas_e_pesos_convertido**. Além disto investigue a correlação entre as alturas e os pesos.